apiVersion: v1
kind: Service
metadata:
  name: kuweb-service
spec:
  type: NodePort
  selector:
    app: kuweb-label
  ports:
  - name: kuweb-port
    # nodeport도 클러스터를 생성하기 때문에 클러스터 포트도 설정할 수 있다.
    port: 80
    targetPort: 8080
    # node에 개방시킬 포트번호를 고정 (미 지정시 매번 랜덤으로 생성)
    nodePort: 30027